import { useState } from "react";
import { format, parseISO, addMinutes } from "date-fns";
import { FileText, Copy, Check } from "lucide-react";
import { useTimelineStore } from "../lib/store";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from "./ui/dialog";

export function DailyBrief() {
  const { events: allEvents, selectedDate, profile } = useTimelineStore();
  const [copied, setCopied] = useState(false);

  const events = allEvents
    .filter(e => format(parseISO(e.startTime), "yyyy-MM-dd") === format(parseISO(selectedDate), "yyyy-MM-dd"))
    .sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime());

  const generateBriefText = () => {
    if (events.length === 0) {
      return `Good morning. The schedule for ${format(parseISO(selectedDate), "EEEE, MMMM do")} is currently clear. No engagements scheduled.`;
    }

    const recipientName = profile.name || "Executive";
    let text = `📅 *DAILY BRIEF FOR ${format(parseISO(selectedDate), "EEEE, MMMM do").toUpperCase()}*\n`;
    text += `Target: ${recipientName} (${profile.position || "Principal"}${profile.company ? `, ${profile.company}` : ""})\n`;
    text += `Total Engagements: ${events.length}\n\n`;

    events.forEach((event, idx) => {
      const startTime = parseISO(event.startTime);
      const endTime = addMinutes(startTime, event.durationMinutes);
      text += `${idx + 1}. *${format(startTime, "h:mm a")} - ${format(endTime, "h:mm a")}* | ${event.title}\n`;
      text += `   • Type: ${event.type.toUpperCase()}\n`;
      if (event.location) text += `   • Location: ${event.location}\n`;
      if (event.attendees && event.attendees.length > 0) {
        text += `   • Attendees: ${event.attendees.join(", ")}\n`;
      }
      if (event.description) text += `   • Notes: ${event.description}\n`;
      text += `\n`;
    });

    text += `Generated by Executive Suite Timeline Manager.`;
    return text;
  };

  const copyBrief = () => {
    const text = generateBriefText();
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Daily briefing copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <button 
          className="flex items-center justify-center gap-2 rounded-2xl bg-secondary hover:bg-accent px-4 py-2.5 text-sm font-semibold text-foreground border border-border shadow-sm transition-all w-full md:w-auto"
          title="Generate Daily Briefing"
        >
          <FileText className="h-4 w-4 text-primary" />
          <span>Briefing</span>
        </button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle>Daily Briefing Summary</DialogTitle>
        </DialogHeader>
        <div className="py-4">
          <textarea
            readOnly
            className="w-full h-80 rounded-2xl border border-border bg-secondary/50 p-4 text-xs font-mono resize-none focus:outline-none"
            value={generateBriefText()}
          />
        </div>
        <DialogFooter>
          <button
            onClick={copyBrief}
            className="w-full flex items-center justify-center gap-2 rounded-xl bg-primary text-primary-foreground py-2.5 text-sm font-semibold hover:opacity-90 transition-all"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied" : "Copy Briefing"}
          </button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
